Reformat tutorials
RoseauTechnologies/Roseau_Load_Flow pull request #115
Opened 2023-08-08 17:48 UTC by benoit9126

- [x] Reformat tutorials notebook into markdown files
- [x] Split the "Advanced tutorial" into several files
- [x] Rename short circuit into short-circuit everywhere
- [ ] Delete the notebooks
- [ ] Delete the docker container build (too complicated and useless with a working conda installation)

2023-08-09 09:10 UTC, alihamdan reviewed
Looks good. I left some suggestions.

2023-08-09 09:10 UTC, alihamdan commented on doc/usage/Connecting_Elements.md
> +The connection of an element to an existing network is automatically done when the elements are built. Let's create
As the example below demonstrates
```suggestion
The connection of an element to an existing network is not automatically done when the elements are built. Let's create
```

2023-08-09 09:10 UTC, alihamdan commented on doc/usage/Flexible_Loads.md
> +* The power for phases `'b'` and `'c'` is 0 VA as expected.
This section (starting from "Here, one can ...") should be moved below the code block that shows the example below

2023-08-09 09:10 UTC, alihamdan commented on doc/usage/Flexible_Loads.md
> +[Euclidean projection](models-flexible_load-projection) has been used.
Same here, move below the code block

2023-08-09 09:10 UTC, alihamdan commented on doc/usage/Short_Circuit.md
> +Looking at the line results of the second bus of the line "line2", which is "bus2" where we added the short-circuit,
```suggestion
Looking at the line results of the second bus of the line `line2`, which is `bus2` where we added the short-circuit,
```

2023-08-09 09:10 UTC, alihamdan commented on doc/usage/Short_Circuit.md
> +Here the potential at phase "a" of bus "bus2" is zero, equal to the ground potential. The sum of the currents in the
```suggestion
Here the potential at phase "a" of bus `bus2` is zero, equal to the ground potential. The sum of the currents in the
```

2023-08-09 14:21 UTC, alihamdan approved these changes

2023-08-10 07:41 UTC, Saelyos requested changes

2023-08-10 07:41 UTC, Saelyos commented on doc/usage/Getting_Started.md
> +* Buses:
The link to `[api-models]` already exists after the short description of the elements. At this points, I think I would prefer to have a link to `/models`

2023-08-10 07:41 UTC, Saelyos commented on doc/usage/Getting_Started.md
> +* `residual`: the precision which was reached by the solver (lower than the tolerance if successful solve).
Maybe add at the bottom a link to `/solvers` ?

2023-08-10 07:41 UTC, Saelyos commented on doc/usage/Getting_Started.md
> +... vs = VoltageSource(id="vs", bus=source_bus, phases="abcn", voltages=source_voltages)
For all the voltage sources, lines and loads, the phases have been specified which is not mandatory. IMO the phases should not be specified in those cases, as there is more chance to do something wrong (for exemple adding an MV line with `"abc"` in a LV network `"abcn"`) without noticing. If the phases are not specified the user will get an error. The phases for those elements should only be done for special cases.

2023-08-10 08:46 UTC, Saelyos approved these changes

2023-08-10 08:46 UTC, merged