Add Qmin and Qmax limits
RoseauTechnologies/Roseau_Load_Flow pull request #133
Opened 2023-09-22 15:07 UTC by Saelyos

Add and optional minimum and maximum limit to the reactive power of flexible parameters #126

2023-09-22 15:46 UTC, alihamdan reviewed
Looks good. Left you a few minor comments.

2023-09-22 15:46 UTC, alihamdan commented on roseau/load_flow/models/loads/flexible_parameters.py
> +            logger.warning("'s_max' has been updated but now 'q_min' is lesser than -s_max. 'q_min' is set to -s_max")
Typo: lesser -> less

2023-09-22 15:46 UTC, alihamdan commented on roseau/load_flow/models/loads/flexible_parameters.py
> +            msg = f"'q_max' must be lesser than s_max ({self.s_max:P#~}) but {self.q_max:P#~} was provided."
Same typo

2023-09-22 15:46 UTC, alihamdan commented on roseau/load_flow/models/tests/test_flexible_parameters.py
Maybe add a test for the case where Smax is changed to a value >Qmax or <Qmin?

2023-09-22 15:46 UTC, alihamdan commented on doc/models/Load/FlexibleLoad/FeasibleDomain.md
> +It is also possible to define a minimum and maximum reactive power value. In that case, the feasible domain is
```suggestion
It is also possible to define a minimum and maximum reactive power values. In that case, the feasible domain is
```

2023-09-22 15:46 UTC, alihamdan commented on doc/models/Load/FlexibleLoad/FeasibleDomain.md
> +The variable `res_flexible_powers` contains the powers that have been really produced by
```suggestion
The variable `res_flexible_powers` contains the powers that have been actually produced by
```
There is another occurrence in this file that I forgot to fix, maybe you can fix it as well.

2023-09-22 15:46 UTC, alihamdan commented on doc/models/Load/FlexibleLoad/FeasibleDomain.md
> +Here, again the complete reactive power range is not fully used.
Also mention the Q constraints. After all this section is about Qmin and Qmax.

2023-09-22 15:48 UTC, alihamdan commented on roseau/load_flow/models/loads/flexible_parameters.py
> +            "q_max": self._q_max,
These should only be added if they are not None. This should fix CI

2023-09-22 17:01 UTC, benoit9126 requested changes
Great! I wrote some minor comments.

Could you please add a line in the changelog?

2023-09-25 08:52 UTC, alihamdan approved these changes

2023-09-25 08:54 UTC, alihamdan commented
> Could you please add a line in the changelog?

@Saelyos you forgot this

2023-09-25 09:15 UTC, merged