Modify the voltage limits of buses
RoseauTechnologies/Roseau_Load_Flow pull request #280
Opened 2024-11-13 16:14 UTC by benoit9126

Close #278

The `Bus` constructor now accepts a nominal voltage (phase-to-phase, in V), a `min_voltage_level` (without unit) and a `max_voltage_level` (without unit). These arguments replace `min_voltage` and `max_voltage`. The `Bus` class now have some additional properties:
- `res_voltages_level`: it retrieves the voltage level of the bus according to the provided phase-to-phase nominal
    voltage;
- `min_voltage_level` and `max_voltage_level`: these properties retrieve the minimum and maximum voltage levels.
- `min_voltage` and `max_voltage`: these properties (that existed before) now compute the minimum and maximum
    voltage (in V) from the nominal voltage and the minimum and maximum levels.

The file format also changed to take into account these changes. If a `min_voltage` or `max_voltage` existed in a file of a previous version, they are lost when upgrading the file.

2024-11-13 17:15 UTC, alihamdan requested changes
Excellent. I just have a few suggestions.

2024-11-13 17:15 UTC, alihamdan commented on roseau/load_flow/models/buses.py
> +    def res_voltages_level(self) -> FloatArrayLike1D | None:
The name should be `res_voltage_levels`. The type must be concrete as it is a return type `Q_[NDArray[np.float64]] | None`.

2024-11-14 08:03 UTC, alihamdan approved these changes
LGTM. One more comment update in the docs.

2024-11-14 08:03 UTC, alihamdan commented on doc/usage/Getting_Started.md
> +... u_min_level = 0.9  # V
Same for the max level
```suggestion
... u_min_level = 0.9  # 90% Un
```

2024-11-14 08:23 UTC, Saelyos approved these changes

2024-11-14 13:28 UTC, merged