ENH: Add `max_loading` on lines and transformers
RoseauTechnologies/Roseau_Load_Flow pull request #285
Opened 2024-11-21 08:46 UTC by benoit9126

Implementation of #279

2024-11-21 13:12 UTC, Saelyos commented on roseau/load_flow/models/lines/lines.py
> +        return Q_(np.maximum(abs(currents1), abs(currents2)) / i_max, "")
Maybe `@ureg_wraps` can be used for this property ?

2024-11-21 13:12 UTC, Saelyos commented on roseau/load_flow/models/transformers/transformers.py
> +
Same

2024-11-21 16:32 UTC, alihamdan requested changes
Thank you. Noticed a few thinks.

2024-11-21 16:32 UTC, alihamdan commented on roseau/load_flow/io/dict.py
> +        transformer_param_data.pop("max_power", None)
The value of `max_power` (when not None) should be used to compute the `max_loading` value on transformers that use this Parameters object. Example:
```python
old_tp = {"id": "old_tp1", "sn": 100_000, "max_power": 80_000, ...}
old_tr = {"id": "old_tr1", "params_id":  "old_tp1", ...}

new_tp = {"id": "old_tp1", "sn": 100_000, ...}  # no more max_power
new_tr = {"id": "old_tr1", "params_id":  "old_tp1", "max_loading": old_tp["max_power"]/old_tp["sn"], ...}

```

2024-11-21 16:32 UTC, alihamdan commented on roseau/load_flow/io/dict.py
> +        transformer_data["max_loading"] = 1
See above, this value is not always `1` if `max_power` was defined

2024-11-21 16:32 UTC, alihamdan commented on roseau/load_flow/io/tests/test_dict.py
> -    tp1.max_power = 180_000
Maybe test `transformer2.max_loading` here instead?

2024-11-21 16:32 UTC, alihamdan commented on roseau/load_flow/models/lines/lines.py
> +        ampacities` of the parameters."""
```suggestion
        `ampacities` of the parameters."""
```

2024-11-21 16:32 UTC, alihamdan commented on roseau/load_flow/models/lines/lines.py
> +            max_loading:
Say that it is not used in the load flow (as we do for all other optional parameters)

2024-11-21 16:32 UTC, alihamdan commented on roseau/load_flow/models/transformers/parameters.py
>          pc: float | Q_[float],
I didn't notice this in your last PR but the parameters `uhv` and `ulv` for the `from_power_factory` method must not be renamed to `up` and `us`. The whole point of this method is that it uses the power factory notation and parameters and converts to them to the proper RLF object.

2024-11-22 09:17 UTC, alihamdan approved these changes

2024-11-22 09:18 UTC, merged